# Generated by Django 4.0.4 on 2022-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletags',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='is_main',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='articles.ArticleTags', to='articles.tags', verbose_name='Тематики статьи'),
        ),
        migrations.AddField(
            model_name='articletags',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleTags', to='articles.article'),
        ),
    ]
